# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  financeiroapi:
    image: financeiroapi
    build:
      context: .
      dockerfile: Financeiro.Api/Dockerfile
    ports:
      - 5036:5036
